### ISSUE TITLE
Review responses for Q78

### ISSUE THREAD

**Issue by ptatian** [NeighborhoodInfoDC/Voices#18]
@lhendey In our check in call today, Ben said that he noticed unexpectedly high percentages of people reporting that they were green card holders or legal residents in places like PG County (question 78). He wondered whether this was a problem of people not properly understanding the question or that the sample was biased toward non-native citizens. I know that we can't necessarily know that, but would you take a look and see if there's anything more we can say about this or whether we may need to address this issue in some way. Thank you.

**Comment by lhendey** [comment]
@ptatian - the wording of Q77 is a bit awkward but I don't think that it really skewed the results. We do have less immigrants than the population but that's probably an issue with the survey itself vs. the specific question. I think Ben was thinking Q78 was asked of everyone instead of only those who are foreign born. I don't think it's crazy that a quarter of immigrants (+/- 15%...) in PG have a green card. We could ask Audrey if she has any insights as to why DC would have a slightly different pattern than the other places on green card vs. other visa vs. undocumented but given the CIs its probably a wash... 
I also don't think Ben was getting that the last category was undocumented.

**Comment by ptatian** [comment]
@lhendey Thanks, Leah. We are just going to need to explain all of that to them. Was Q77 our wording, or GfK's?

**Comment by lhendey** [comment]
@ptatian - the wording was ours...

**Comment by lhendey** [comment]
@ptatian  = closed this issue.
